name = "emergency-resource-directory"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "emergency-resources"
database_id = "7e596b18-c563-4e29-ac86-c72eb2dfe2f5"

[[kv_namespaces]]
binding = "RATELIMIT"
id = "64c575fc1b6e49bd866ab8096324adb2"

[ai]
binding = "AI"
